services:
  dns-collaborate-ui:
    image: registry.ohrenpirat.de:5000/mwildt/ceh-trainer-ui:latest
    build:
      context: .
      dockerfile: ceh-trainer-ui.dockerfile
    ports:
      - 3010:3010
    environment:
      - API_SERVICE_HOST=http://192.168.178.25:8080
      - LISTEN_ADDRESS=:3010